### ISSUE TITLE
Some issues in l10n_th_address

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-thailand#1]
@kittiu some issues I noticed in l10n_th_address:

- [ ] the version number must have five parts (10.0.1.0.0)
- [ ] in the data and csv files there are ids with `base.` or `bas.` as a prefix. Is that intended? If you look at the travis log, it warns about it

In general, even if you are working alone it's better to do pull requests so you can check travis outcome before merging.

**Comment by kittiu** [comment]
@sbidoul Thanks for the comment. I will always use PR in the future.
For the .csv, actually what I want is to use xml with noupate="1". As data is big, .csv takes time in every update.
Do you know if there is way to convert from .csv to xml data file?

**Comment by dreispt** [comment]
AFAIK using a different module prefix, such as `base.` does not achieve the `noupdate` effect.
Maybe you could write a Python script to do that conversion.
Or, you could use a post install hook to run code updating the `noupdate` flag on all the `ir.model.data` records for those XML Ids.

**Comment by kittiu** [comment]
This module is merged, so I close this case.
