### ISSUE TITLE
base_location_thailand ไฟล์ข้อมูล zip หายไป

### ISSUE THREAD

**Issue by poonlap** [OCA/l10n-thailand#105]
![image](https://user-images.githubusercontent.com/16228313/75085576-52effb00-555d-11ea-9319-f17f13b0ca6a.png)

ผมลองทดสอบโมดูล https://github.com/OCA/l10n-thailand/tree/13.0/base_location_thailand
พบว่าไฟล์ ZIP หาย repo ของ ecosoft หายไปครับ. เข้าใจว่าน่าจะต้องแก้โค้ดให้ชี้มาที่ OCA 

แต่ผมลองเข้าไปดูที่ 
https://github.com/OCA/l10n-thailand/tree/13.0/base_location_thailand/data
ก็ไม่มี ZIP เช่นกันครับ

**Comment by kittiu** [comment]
@poonlap thanks for your reporting.
@ps-tubtim would you change the data to get loaded from the addon itself?
Thanks!

**Comment by ps-tubtim** [comment]
@poonlap ขณะนี้ได้แก้ไขโค้ดให้ดึงข้อมูลจากไฟล์ .txt แทน .zip ค่ะ เพื่อที่จะดึงข้อมูลจากในโมดูลได้เลย และจาก error ในภาพน่าจะเป็นโค้ดเก่า ลอง pull โค้ดให้ล่าสุดดูนะคะ แล้วลองอีกครั้งค่ะ

**Comment by poonlap** [comment]
@ps-tubtim อันนี้ test จาก OCA  branch 13.0 ครับ. ดูในโค้ดอัปเดทแล้ว แต่เวลารันก็ยัง error เหมือนเดิมครับ

`web_1  | 2020-02-22 17:47:35,418 1 INFO demo werkzeug: 172.20.0.1 - - [22/Feb/2020 17:47:35] "POST /web/dataset/call_button HTTP/1.1" 200 - 13 0.006 0.688
web_1  | 2020-02-22 17:47:35,452 1 INFO ? werkzeug: 172.20.0.1 - - [22/Feb/2020 17:47:35] "GET /web/static/src/xml/crash_manager.xml?debug=1582368455446 HTTP/1.1" 200 - - - -
web_1  | 2020-02-22 17:48:03,024 1 INFO demo werkzeug: 172.20.0.1 - - [22/Feb/2020 17:48:03] "POST /web/dataset/call_kw/city.zip.geonames.import/write HTTP/1.1" 200 - 4 0.002 0.004
web_1  | 2020-02-22 17:48:03,043 1 INFO demo werkzeug: 172.20.0.1 - - [22/Feb/2020 17:48:03] "POST /web/dataset/call_kw/city.zip.geonames.import/read HTTP/1.1" 200 - 3 0.002 0.003
web_1  | 2020-02-22 17:48:03,099 1 INFO demo odoo.addons.base_location_geonames_import.wizard.geonames_import: Starting to download https://github.com/ecosoft-odoo/l10n-thailand/raw/13.0-add-base_location_thailand/base_location_thailand/data/en/TH.zip
web_1  | 2020-02-22 17:48:03,674 1 WARNING demo odoo.http: ('Got an error 404 when trying to download the file https://github.com/ecosoft-odoo/l10n-thailand/raw/13.0-add-base_location_thailand/base_location_thailand/data/en/TH.zip.', '')`

**Comment by ps-tubtim** [comment]
@poonlap หลังจาก update ตัวโค้ดแล้ว ลอง restart server ดูนะคะ เพราะจาก error ยังเป็นการดึงข้อมูลจาก .zip อยู่ และจากการ test ที่ runbot ก็สามารถใช้งานได้ตามปกตินะคะ

**Comment by poonlap** [comment]
@ps-tubtim  โอเคครับ เจอข้อผิดพลาดแล้วครับ ผมผิดเองครับ
พอดีผมมี addons path  อยู่หลายที่ ตอนที่ทดสอบ ระบบไปใช้โมดูลตัวเก่า ที่เจอใน path ก่อน เลยทำให้เข้าใจผิด. ตอนนี้โอเคแล้วครับ.
