### ISSUE TITLE
โมดูล base_location_thailand กรณี ENV ภาษาไทย

### ISSUE THREAD

**Issue by poonlap** [OCA/l10n-thailand#106]
กรณีผู้ใช้ environment  ภาษาไทย ไม่สามารถ import ข้อมูลได้ครับ.

`<field name="location_thailand_language" widget="radio" attrs="{'invisible': [('country_name', '!=', 'Thailand')]}"/>`

![image](https://user-images.githubusercontent.com/16228313/75131911-8b333d00-5707-11ea-968a-fa253b194615.png)

import ได้ แต่จะได้ข้อมูลจาก  http://download.geonames.org/export/zip/TH.zip ตามปกติครับ.

**Comment by ps-tubtim** [comment]
@poonlap ขอบคุณที่ช่วยรีวิวนะคะ ตอนนี้ได้ทำ PR แก้บักแล้วค่ะ https://github.com/OCA/l10n-thailand/pull/108

**Comment by poonlap** [comment]
@ps-tubtim ขอบคุณครับ
ผมทดสอบเพิ่มเติม view ผ่านแล้วครับ. import ตอน ENV ภาษาไทยได้.

แต่ใน model ตอนกรอกให้ completion จะไม่เติม street2 ให้เนื่องจาก `self.country_id.name == "Thailand"`  คิดว่าต้องไปทำฟังก์ชั่น is_thailand ที่นี่ด้วยครับ

```
   @api.onchange("zip_id")
    def _onchange_zip_id(self):
        res = super()._onchange_zip_id()
        if self.zip_id and self.country_id.name == "Thailand":
            address = self.zip_id.city_id.name.split(", ")
            self.update({"street2": address[0], "city": address[1]})
        return res
```

**Comment by kittiu** [comment]
ขออภัยนะ สรุปเคสนี้ยังค้างไม๊ครับ

**Comment by poonlap** [comment]
@kittiu  แบ่งเป็น 2 ส่วนนะครับ
1. ตอน import  -> ได้รับการแก้ไข และผ่านแล้ว
2. ตอน กรอกข้อมูล -> เพิ่งพบ. ถ้าเป็น ENV Thai ไม่เติม Street 2 ให้ ครับ

**Comment by poonlap** [comment]
เช็คโมดูลที่เพิ่ง merge เข้าไป โอเคแล้วครับ ขอบคุณครับ
