### ISSUE TITLE
Typo error (data) โมดูล base_location_thailand

### ISSUE THREAD

**Issue by poonlap** [OCA/l10n-thailand#109]
![image](https://user-images.githubusercontent.com/16228313/75742285-bf2de400-5d3f-11ea-844b-17761695a15a.png)

ไฟล์ data/TH_en.txt

Pahtum Wan  ที่ถูกต้องต้องเป็น Pathum Wan ครับ

**Comment by ps-tubtim** [comment]
@poonlap สามารถเข้าไปรีวิวโค้ดใน https://github.com/OCA/l10n-thailand/pull/108 ได้เลยค่ะ
