### ISSUE TITLE
OCA-130320: Multi Payment Method, many invoices 1 payment with different method

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#119]
เคสนี้ไม่แน่ใจว่าต้องการอะไรนะครับ ถ้ามี Use Case จะช่วยได้ @Siraparn

**Comment by sansirit** [comment]
ปกติสามารถบันทึกรับเงินหลายครั้ง ใน 1 invoice อยู่แล้วนะครับ
