### ISSUE TITLE
[RFC] Automatic currency update for Thailand

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#128]
![image](https://user-images.githubusercontent.com/1973598/77282646-1b5fa480-6cfd-11ea-864a-b61c7ffd7e0b.png)

**Comment by kittiu** [comment]
I.e., Bank of Thailand? Bangkok Bank, etc...

**Comment by Saran440** [comment]
I think thailand can't do this because many company in Thailand
used currency rate from bank partner and
each bank has
- no .xml file update daily day.
- no api currency rate

**Comment by sansirit** [comment]
According to an annoucement from Ministry of Finance [here](http://www.rd.go.th/publish/fileadmin/user_upload/kormor/newlaw/mfexchange2563.pdf), we must get an official reference exchange rate from Bank of Thailand which can be obtained from [here](https://www.bot.or.th/thai/_layouts/application/exchangerate/exchangerate.aspx).

I checked the Bank of Thailand API page. There is an API to get daily_ref_rate, more detail [here](https://apiportal.bot.or.th/bot/public/node/504). We must create an account to use the API [here](https://apiportal.bot.or.th/bot/public/start). 

The API for daily exchange rate is free. The BoT API use OAuth with client-id and client-secret.

![image](https://user-images.githubusercontent.com/7272259/95344105-76e13080-08e3-11eb-90bc-1202ca344dee.png)

**Comment by ps-tubtim** [comment]
@sansirit PR: https://github.com/OCA/l10n-thailand/pull/156 already created. Could you review this?

**Comment by kittiu** [comment]
Thanks @sansirit . Also any idea for  other commercial bank?

**Comment by kittiu** [comment]
https://developer.scb/#/login
อันนี้เป็นข่าวที่เค้าประกาศเปิด API เมื่อปีที่แล้ว
https://techsauce.co/news/scb-open-api

Credit: @WM. from line group.

**Comment by sansirit** [comment]
[developer.scb](https://developer.scb) ผมไม่เห็นเรื่อง currency exchange เลยครับ

currency exchange ผมเจอแค่ API ของธนาคารแห่งประเทศไทย ซึ่งเป็นค่าเฉลี่ยของอัตราแลกเปลี่ยนจากธนาคารพาณิชย์อีกที
