### ISSUE TITLE
Is the setting in this repo ready for PR?

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#14]
@pedrobaeza @sbidoul
Sorry for bothering you here. We want to start bringing addons to this repo. We just not sure if the setting is ready, as our PRs have error like in this travis log.
https://travis-ci.org/OCA/l10n-thailand/jobs/527116314
Seem like something is missing on the setting?
Thank you so much in advance.... _/|\_

**Comment by pedrobaeza** [comment]
Hi, @kittiu, yes, it is. I have adjusted .travis.yml files for 11.0 and 12.0 for saving one build. Any problem you find, please tell us.
