### ISSUE TITLE
Tax Report (Suggestions)

### ISSUE THREAD

**Issue by Boss1669** [OCA/l10n-thailand#147]
โดยปกติ Report Tax ออกมาจะเป็นดังรูปครับ
![image](https://user-images.githubusercontent.com/26357404/85492522-7f954b80-b5ff-11ea-88f9-5bf7ee8f2037.png)
โดยผมคิดว่าในส่วนช่อง Reference ควรจะ Ref ถึง INV นั้นๆหรือป่าวคับ เช่น RINV/2020/0272
![image](https://user-images.githubusercontent.com/26357404/85492679-bf5c3300-b5ff-11ea-90fe-510ba2ea3c75.png)
เพราะผมคิดว่าข้อมูล Reference สำคัญกับ RINV มากพอควรเพราะจะได้รู้ว่า Refund ของ Invoice ไหนเพื่อเป็นข้อมูลส่งให้สำนักงานบัญชี

**Comment by kittiu** [comment]
อันนี้ใช้ version อะไรครับ, 12 หรือ 13

**Comment by Boss1669** [comment]
@kittiu 13 ครับผม

**Comment by kittiu** [comment]
สวัสดีครับ กรณี reference ทางผมได้ปรึกษากับนักบัญชีแล้ว คิดว่า reference กลับไปที่ เลขที่เอกสารของ credit note น่าจะโอเคแล้ว เพราะสาารถไปที่เอกสารนั้นๆแล้วสาวต่อไปได้

อีกเรื่องที่อาจไม่เกี่ยวกับเคสนี้ จะแจ้งว่าโมดูลนี้มี feature เพิ่มเติมนะครับ ให้สามารถรันเลขที่ Tax Invoice เป้น sequence ต่างหากได้ เป็น sequence เดียวกันทั้ง Customer Invoice และ Customer Refund ได้

![image](https://user-images.githubusercontent.com/1973598/85972981-9ec71b00-b9fb-11ea-81df-78a4632b95b8.png)

**Comment by Boss1669** [comment]
@kittiu แต่ reference ที่เป็นอยู่ตอนนี้มันไม่ได้ reference ไปที่เลขที่เอกสาร credit note ของ inv นั้นะครับเท่าที่ดูจากโค้ดตอนนี้เหมือนจะ reference ไปเลขเอกสารของ customer inv นะครับ 
https://github.com/OCA/l10n-thailand/blob/337642d9efd8755a12c97fac7762497639305ad6/l10n_th_tax_report/reports/tax_report.xml#L165

**Comment by kittiu** [comment]
https://github.com/OCA/l10n-thailand/blob/13.0/l10n_th_tax_report/reports/tax_report.py#L57-L58

name นี่ต้งใจให้ refer กลับไปที่ move_name หรือ payment.communication แล้วแต่กรณี (เพราะกรณี tax receipt เราก็ยังอยากให้ ref กลับไปที่ invoice ต้นทางเหมือนกัน)

ซึ่งในกรณี Credit Note เช่น RINV-xxx ก็จะ reference กลับไปที่ RINV-xxx ตามที่คุณ @Boss1669 บอกเหมือนกันนี่ครับตามรูปด้านบนที่ส่งมา

หรือว่ามีกรณีไหนที่ยังผิดอยู่ลองส่งมาครับ
