### ISSUE TITLE
New thai accounting model

### ISSUE THREAD

**Issue by dynaz** [OCA/l10n-thailand#148]
https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
(deleted by @kittiu)

Thai accounting for 13  and 11

**Comment by dynaz** [comment]
มีบั๊ก อยู่บ้างคับคับ เพราะยังไม่ได้เก็บดีเทลคับ

**Comment by kittiu** [comment]
สวัสดีครับ อันนี้คืออะไรนะครับ ต้องการให้เราช่วยอะไรไมีครับ

**Comment by dynaz** [comment]
เป็นตัวบัญชีไทย ที่ทีมผมทำมาใน v13 คับ เผื่อจะใช้เป็นไอเดียในการต่อยอดทำระบบ localize ไทยคับ

**Comment by thitithup** [comment]
ฝากรบกวน admin ลบ Post ที่ให้ Download ด้วยครับ ตรวจสอบแล้วเป็น Source Code ที่ผมเขียนขึ้นมา (INECO) และเป็นของลูกค้าบริษัท SystemS ซึ่งทางผู้ Post (dynaz) ได้ละเมิดนำ Source Code ดังกล่าวมาเผยแพร่โดยไม่ได้รับอนุญาติ

**Comment by kittiu** [comment]
เอาออกให้แล้วนะครับ แต่ขออนุญาตไม่ลบ issue นี้นะครับ เก็บไว้ history ที่เกิดขึ้นตามจริง

**Comment by kittiu** [comment]
OCA เราสนับสนุนให้เกิดการแบ่งปัน แต่ไม่สนับสนุนการใช้ซอฟท์แวร์ละเมิดลิขสิทธิ์ในทุกๆทางนะครับ
แต่ถ้าใครอยากแชร์โค้ดจริงๆ เพื่อประโยชน์ส่วนรวม OCA ก็ยินดีครับ (แต่ก็ต้องผ่านการ code review ตามปกติก่อน)

**Comment by thitithup** [comment]
ขอบคุณครับ
