### ISSUE TITLE
Convert Amount Text to Thai Problem.

### ISSUE THREAD

**Issue by kotchasaan** [OCA/l10n-thailand#160]
ทดสอบการใช้ module Convert Amount Text to Thai ตอนนี้ยังไม่สามารถใช้งานได้ใช่มั้ยครับ ทดลองใช้แล้วขึ้นเป็นภาษาอังกฤษและสกุลเงินยูโร
สภาพแวดล้อมที่ใช้
- odoo 13
- ติดตั้ง default เป็นภาษาไทย
- กำหนดสกุลเงินเป็นไทยบาท

**Comment by kittiu** [comment]
@Saran440 you are the best to answer this :)

**Comment by Saran440** [comment]
@kotchasaan default num2words ของ odoo13 คือ version 0.5.6 ซึ่งไม่รองรับภาษาไทยครับ
ต้องเปลี่ยน version num2words เป็น version 0.5.7 ขึ้นไปครับถึงจะรองรับภาษาไทย

Refenrece : https://github.com/OCA/l10n-thailand/blob/13.0/l10n_th_amount_to_text/readme/CONFIGURE.rst

**Comment by kotchasaan** [comment]
ขอบคุณมากครับ

**Comment by kotchasaan** [comment]
แก้ไขเรียบร้อยครับ
