### ISSUE TITLE
How to setting "Period" in Thai TAX Report selection parameter? 

### ISSUE THREAD

**Issue by kotchasaan** [OCA/l10n-thailand#163]
สวัสดีครับผมทดสอบการพิมพ์รายงานภาษี(ไทย) ใน wizard ที่ให้เลือก Period ก่อนการพิมพ์รายงานไม่ทราบว่าต้องติดตั้งส่วนเสริมตัวไหนเพิ่มอีกหรือไม่ครับ หรือต้องไปตั้งค่าในส่วนไหนผมลองหาแล้วไม่พบ

**Comment by kittiu** [comment]
ใน Odoo version หลังๆ Odoo เค้าตัดเรื่อง period ทิ้ง แต่รายงานเราต้องการความสะดวกในการรันรายงานแต่ละ Period เลยใช้ module date_range ของ OCA มาช่วย ลองไปศึกษาดูนะครับ แล้วให้สร้างมันขึ้นมาก่อน

https://github.com/OCA/server-ux/tree/13.0/date_range

**Comment by kotchasaan** [comment]
ขอบคุณครับผม

**Comment by kotchasaan** [comment]
ทดสอบเรียบร้อยครับ สามารถพิมพ์รายงานภาษีได้สวยงามครับ ขอบคุณอีกครั้งครับ

**Comment by kotchasaan** [comment]
+
