### ISSUE TITLE
การบันทึกตั้งเจ้าหนี้/ลูกหนี้ในระบบบัญชี

### ISSUE THREAD

**Issue by kotchasaan** [OCA/l10n-thailand#165]
เรียนสอบถามการตั้งหนี้ทั้งฝั่งเจ้าหนี้/ลูกหนี้ในเวอร์ชั่น 13 เราต้องออกใบกำกับภาษี(Tax Invoice) ก่อนถึงจะบันทึกบัญชีได้ประเด็นอยู่ที่
1. ต้องการบันทึกบัญชีในฝั่งเจ้าหนี้หลังจากได้รับใบแจ้งหนี้จากเจ้าหนี้ ซึ่งเราจะยังไม่ได้รับใบกับกับภาษีจากทางฝั่งเจ้าหนี้
2. ต้องการบันทึกบัญชีในฝั่งลูกหนี้หลังจากเราวางบิลไปแล้วแต่เรายังไม่ออกใบกำกับภาษีให้ลูกหนี้

ปัจจุบันผมใช้วิธีใส่เลขอะไรก็ได้ไปก่อนและเปลี่ยนโค้ด GL เป็นภาษียังไม่ถึงกำหนดเพื่อให้บันทึกบัญชีไปก่อน หรืออีกแนวทางหนึ่งคือลบรายการใน Tax Invoice ออก

อยากจะสอบถามว่าวิธีที่ถูกต้องควรทำอย่างไร

**Comment by Saran440** [comment]
ลองดู module l10n_th_tax_invoice ว่าตอบโจทย์ไหมครับ

https://github.com/OCA/l10n-thailand/tree/13.0/l10n_th_tax_invoice

**Comment by kittiu** [comment]
ตามที่ @Saran440 บอก ถ้าหมายถึง Undue Tax (tax point at payment) โมดูลนี้ก็ตอบโจทย์อยู่แล้วครับ ต้องเซตอัพตาม README นิดหน่อย
