### ISSUE TITLE
Enable transifex

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-thailand#2]
@pedrobaeza Transifex is failing here. Do you know if there is something special to do to activate it?

**Comment by pedrobaeza** [comment]
Transifex key is correct?

**Comment by sbidoul** [comment]
Is there a different one for each repo? If yes, where is the procedure to generate a new one?

**Comment by pedrobaeza** [comment]
Yes, of course! You have it on the sample file: https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L45

I can generate it for you if you want.

**Comment by sbidoul** [comment]
> I can generate it for you if you want.

That would help indeed, thanks!

**Comment by pedrobaeza** [comment]
Here you have it:
```
  secure: "yaEEMJ+b5wpySGxYHPqUbDCgPwHtLhc8lwk7kyc7zJQ09+NRQFHlmuCv3FUx6s2IYi2tl4zloW7ne/hjPR47eUnxc2ok+aHZzxsjn1/90Ty37MW9Fhd2sVrTQwB5GkbaX7A7gE7YPJir2LdvF5OD24Q3e3nSp33vnSKah4qRtIdjOHtKSf6TS1nM22OT8bPscBVt3mcek9zPxUwMfSCDFJ7TZZ1/Ab9NwhHDXNqbo3tYQMvBuNT+TR9SRFb8MfHLvZ0hlLcfTL4hua8nlFQSxTjx/p4LQRbM6Dk3oxlq6pijNxW4Q1S8K/Robj8KDv2R7d+mJkCaZc+zbT/o1CryCJbqQLW+cjprC8O5uBU4nOrdvaWHjfvmieKBX/sNAmEDc7ApI9zDGFXUSTyqO7inzMK6nYZ2ktwDuP+5+7dpFnQYYzGqnNIE+GDLA2wxKd9XLKz27aptAsfH4xSkIlXramzALr/uTfuet5wLFPstlOhY9P0QFRhB2VCWsFQmhYyR1e3Yik8ZlRGcXyRUsAZXbefT+CL9YrUtm+tNObYAuiiFgc80s3d4skdj+AmlnJTfi6E2lydgm4m3lZBO/XgoylRXXC7NJ/jxbrKYT5ClqRsnF3z3luYeKn6/eKw5UEYt6ibNw3MI6WSYm9AY/UbVjqhFMEMnKSkEEbsG6nEVAwU="
```

**Comment by kittiu** [comment]
Thank you. This key I should put it in our travis.yml, correct?

**Comment by pedrobaeza** [comment]
Yeah, that's it

**Comment by kittiu** [comment]
We start to having some new contributors. You guys welcome to provision once in a while if not too busy :)

**Comment by sbidoul** [comment]
@kittiu we abandoned transifex about 2 years ago. We now have weblate at https://translation.odoo-community.org/ and there you have https://translation.odoo-community.org/projects/l10n-thailand-12-0/ and https://translation.odoo-community.org/projects/l10n-thailand-13-0/.

**Comment by kittiu** [comment]
Thank you Stephane, we will take a look at it.
