### ISSUE TITLE
Can't install module Thai Localization - Withholding Tax (multi taxes)

### ISSUE THREAD

**Issue by komsan-S** [OCA/l10n-thailand#201]
i'm trying install module  module Thai Localization - Withholding Tax (multi taxes), but i found error as a picture
![Screenshot from 2020-11-13 14-56-47](https://user-images.githubusercontent.com/74167464/99043868-72cebf80-25c1-11eb-9575-3469db605965.png)

How to fix the  @problem?

Thankyou

**Comment by kittiu** [comment]
The error is on account_payment_multi_deduction. Not related with Withholding Tax.
Where did you get that module?
