### ISSUE TITLE
Feedback Withholding Tax (Multi)

### ISSUE THREAD

**Issue by Cncd10** [OCA/l10n-thailand#202]
I found **something wrong**. When I create WHT  Multi
**_case 1._**
I choose "Type of Income" ---> 2. ค่าธรรมเนียม ค่านายหน้า
![Selection_224](https://user-images.githubusercontent.com/71874552/99044478-65660500-25c2-11eb-87ad-19463832daa1.png)
and Print WT Certificate (PDF)
![Selection_225](https://user-images.githubusercontent.com/71874552/99044556-84649700-25c2-11eb-94ef-8ba6ce484b25.png)

I see this case in "Type of Income" --> 1, 2, 3

**_case 2._**
I choose "Type of Income" ---> 4. ดอกเบี้ย, 4. เงินปันผล เงินส่วนแบ่งกำไร
![Selection_226](https://user-images.githubusercontent.com/71874552/99045036-49169800-25c3-11eb-97bb-f5b1a178ff30.png)
and Print WT Certificate (PDF)
![Selection_227](https://user-images.githubusercontent.com/71874552/99045052-50d63c80-25c3-11eb-9aa7-c52bfa482178.png)

I see this case in "Type of Income" --> All No.4

**Comment by kittiu** [comment]
@Saran440

**Comment by Saran440** [comment]
Fixed #172 
Case 1 > gorup by type in wt lines
Case 2 > I can't reproduce your case. May be your version wkhtmltopdf is not support.

My test
![Selection_002](https://user-images.githubusercontent.com/20896369/99182244-63d54200-2766-11eb-92af-60d9d7aa70d5.png)

Result
![Selection_003](https://user-images.githubusercontent.com/20896369/99182247-6e8fd700-2766-11eb-84fd-4bc28bbffa00.png)


Could you update you code and test again.
Thank you for your reviewed.
