### ISSUE TITLE
l10n_th_tax_invoice  version: 13.0.2.2.2 , error 

### ISSUE THREAD

**Issue by modnoting** [OCA/l10n-thailand#212]
เออเลอร์ตามลิ้งค์ภาพครับ 
เกิดตอนทำรายการ customer >> invoice >> register payment
https://drive.google.com/file/d/1wLm5wtpm6zit1X2Lh8deElI8K8DSPqYc/view?usp=sharing
มีใครเจอเหมือนผมไหมครับ

**Comment by kittiu** [comment]
ลองเอาล่าสุดไปนะครับน่าจะแก้ไขไปแล้ว 13.0.2.2.3
ช่วงหลังปรับไปหลายอย่าง

**Comment by modnoting** [comment]
ครับ ขอบคุณครับ
