### ISSUE TITLE
Function "Clear Tax" (l10n_th_tax_invoice)

### ISSUE THREAD

**Issue by ToonBS** [OCA/l10n-thailand#285]
Function "Clear Tax" Is it posible to date Jounale Date as the same of the Tax Date to support case: tax date is not same period of the payment ?

On Payment
![image](https://user-images.githubusercontent.com/79127650/157249114-22d19003-7609-475b-9d5e-a70acc20277b.png)

On Journal Entry Cash Basis
![image](https://user-images.githubusercontent.com/79127650/157249267-19b72e0d-7221-4f6d-83e6-e6eda6345545.png)

**Comment by kittiu** [comment]
@Saran440 do we have this option? I remember you did?

**Comment by Saran440** [comment]
From v14 https://github.com/OCA/l10n-thailand/pull/272 (v13 i'm not sure that supported, please check)

1. Go to menu Invoicing > Accounting > Tax invoices
2. Select your tax > edit Report Date to period that you need
![Selection_017](https://user-images.githubusercontent.com/20896369/196090110-c3b1dff0-087e-4be4-a0d5-764d534b7e7e.png)

**Example**
Tax Invoice Date = 01/03/2022
Report Date = 30/04/2022 (1 month)

When you filter tax (Invoicing > Reporting > Thai Tax Report) and select date 01/04/2022 - 30/04/2022
you will found it.
