### ISSUE TITLE
ต้องการออกใบกำกับภาษี สำหรับค่าบริการ

### ISSUE THREAD

**Issue by yukihima** [OCA/l10n-thailand#287]
ในการออกอินวอยซ์ จะมีแสดงให้เห็นเลยว่า ค่าบริการเท่าไหร่
พอรับชำระ จะต้องแยก ใบเสร็จเป็น
1. ใบเสร็จค่าสินค้า (ไม่มีแวท)
2. ใบเสร็จ/ใบกำกับภาษี (ค่าบริการ)

ระบบ odoo ทำได้ไหมคะ ทำตรงไหนคะ

**Comment by kittiu** [comment]
1 invoice และทำจ่ายทีเดียว 1 payment แต่ต้องการแยกใบเสร็จหรือครับ
ไม่น่าทำได้นะครับ มีเคสแบบนี้ด้วยหรือครับ
