### ISSUE TITLE
"l10n_th_tax_report" Not support vat 0% 

### ISSUE THREAD

**Issue by ToonBS** [OCA/l10n-thailand#291]
Thai Tax Report not support case vat0%

Ex. On Vender bill
![image](https://user-images.githubusercontent.com/79127650/182081949-0be04128-2382-41a7-9e7c-1948c9fff10a.png)

On select parameter "Thai Tax Report"
![image](https://user-images.githubusercontent.com/79127650/182082035-ccf01d95-a5e2-49f0-9cc8-24ffe97fed15.png)

On display view of thai tax report
![image](https://user-images.githubusercontent.com/79127650/182082133-30661be4-b17c-41bc-a3f9-b7ec4dd610d7.png)

**Comment by kittiu** [comment]
Yes Odoo core do not create move if it is 0.0
There was debate but seem no progress. You will need to fix into the core.

**Comment by Saran440** [comment]
In version15, Module `l10n_th_account_tax` is support vat 0% in system.
Thank you for your feedback issue.

Here to fix : https://github.com/OCA/l10n-thailand/blob/15.0/l10n_th_account_tax/models/account_move.py#L722
