### ISSUE TITLE
Runbot Icon

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#4]
@pedrobaeza do you know how to enable the Runbot icon? I try to imitate from here. but what is the repo_id? Thanks!
[![Runbot Status](https://runbot.odoo-community.org/runbot/badge/flat/${REPO_ID}/${BRANCH_NAME}.svg)](https://runbot.odoo-community.org/runbot/repo/github-com-oca-${REPO_NAME}-${REPO_ID})

**Comment by pedrobaeza** [comment]
Look here: https://github.com/OCA/maintainer-tools/blob/master/tools/repos_with_ids.txt#L135

**Comment by kittiu** [comment]
@pedrobaeza Thanks!

**Comment by kittiu** [comment]
The icon does not exists for this repo. What to do?
https://runbot.odoo-community.org/runbot/badge/flat/238/10.0.svg

**Comment by pedrobaeza** [comment]
Is there any build already done?

**Comment by kittiu** [comment]
Yes, now I can click on the icon (but no pic) and see runbot.
https://runbot.odoo-community.org/runbot/repo/github-com-oca-l10n-thailand-238

**Comment by pedrobaeza** [comment]
Maybe it's required some time for generating it. Let's wait till tomorrow or so. I don't control that aspects of Runbot. @moylop260, maybe you can help.
