### ISSUE TITLE
install module l10n_th_withholding_tax_cert_form but transaction don't show

### ISSUE THREAD

**Issue by Sabsung** [OCA/l10n-thailand#41]
i am somchart download module for thailand localization but system don't show. help me please

**Comment by kittiu** [comment]
Please describe your steps. You can also paste pictures.

**Comment by Sabsung** [comment]
สวัสดีครับผม
        ผมสมชาติ จับสังข์ ดำเนินการติตดั้ง module ในส่วนของ WT
แล้วนะครับผมแต่ว่าชื่อคำอ่านเป็นภาษาอังกฤษต้องทำอย่างไรครับผมๆทำการเปลี่ยน
currency เป้น thb แล้วนะครับผม
ขอบคุณครับ

Mr.Somchart Jabsung
Tel.0804457374

**Comment by anisus77** [comment]
hi, i have the same probleme when using account.payment.group , how to fix that problem
thx

**Comment by anisus77** [comment]
sorry , i found the prob, i needed to reactivaite menu paiement wich was desactivated by another model

**Comment by kittiu** [comment]
ถ้ามีคำถามเพิ่ม เปิด issue ใหม่นะครับ รบกวนบอกด้วยว่าใช้ของ version การแปะรูปจะช่วยได้เยอะครับ
