### ISSUE TITLE
Discussion / Design on Localized Tax system (thailand)

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#5]
Based on many trials and errors, we though we developed complete understanding and addons for Thailand in v8. But since, v9+, the structure of accounting is changed (especially the remove of account_voucher), it is not straight forward to update it to v10.

I have explained what we did in v8 here --> https://docs.google.com/document/d/1CtEsZfyY8UxjA9FUiE8GcHYP7xH7CfW85Zp8gDS4xlE/edit#

Questions,
* Do you think the concept of Undue VAT and Withholding Tax I explined in the document can be generic enough to be out of Thai Localization.
* We have some difficulties with v10 accounting. Anyone has experiences with it or ways to overcome?
  1. No more Customer/Supplier Payment window to track the payment of multiple invoice lines separately.
  2. Odoo tend to record account.move in summary, rather than in detailed.

**Comment by dreispt** [comment]
These questions are well put, but you probably want to address them to a larger audience.
I suggest you to advertise this discussion in the OCA contributors mailing list.

**Comment by kittiu** [comment]
@dreispt I already sent :)
I also just found v10 CE module account_tax_cash_basic that might answer the Undue VAT question (some scenario). I will study more on it, may be it can be used as base module.

Still waiting for other opinion or pointers!
