### ISSUE TITLE
Thai Localization as discussed with Odoo for v13

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#50]
**Points of discussion**

* Vendor Tax Invoice
  * New fields `tax_invoice_number` and `tax_invoice_date` in account.move.line
  * VAT -- Ability to input it directly in Supplier Invoice window.
  * Undue VAT -- Cash basis journal should not post before + ability to input it directly in Payment window.
  * VAT Report -- Use new 2 new fields in tax report (Vendor Tax only)

* WHT Cert
  * Multiple deduction on Payment window.
  * New WHT Cert window
  * New menu WHT Cert Line for reporting purpose.

* Account Billing
  * Use follow up report in Odoo Enterprise

* Bank In Transit
  * Use Journal with option "Post at Bank Reconcilation
  * Then, use Bank Statement to reconcile to bank, it will be posted.
  * Note: not really what we expect, it is just not yet posted, not that there is real in-transit account.

**Comment by poonlap** [comment]
Hello K. Kitti

How about migrating V12 to V13?  I think at least l10n_thailand_partner can be done first.

**Comment by kittiu** [comment]
We plan to do so. But now we are quite busy with other task at hand. Are you also programmer? You can help make PR for that is needed too :)
PS: It is good to know that there are interest in our project.

**Comment by kittiu** [comment]
Note: the about are just short note on what I discuss with Odoo people, in order to bring Thai localization (mainly Tax and Withholding Tax) into standard Odoo.
But we will also do our own OCA module too.

**Comment by kittiu** [comment]
Archived.
