### ISSUE TITLE
[13.0][TODO] ภาษีซื้อ/ภาษีขายไม่ถึงกำหนดชำระ + Report

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#68]
เคสนี้ได้มีการทำไว้บ้างแล้ว

* Code: https://github.com/OCA/l10n-thailand/tree/13.0/l10n_th_tax_invoice
* Guide: https://ecosoft-odoo.blogspot.com/2020/01/odoo-13-l10nthtaxinvoice.html

อาจเริ่มต้นด้วยการช่วยทดสอบและบอกเคสที่ยังไม่ครอบคลุม หรือ หากมี Module ที่ดีกว่านี้สามารถทำ PR ขึ้นมาเสนอแนะได้

**Comment by dynazo** [comment]
👍
