### ISSUE TITLE
[13.0][TODO] Withholding Tax Cert + Report

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#69]

**Comment by Sabsung** [comment]
พี่ kitti
   ผมรบกวนสอบถามหน่อยนะครับผม พอดีผมทำการลง WHT ใน Version 12 CE นะครับผม แต่คำอ่านที่แสดงเป็น .three hundred euro, zero cents. ในส่วนของ ช่อง รวมเงินภาษีที่หักนำส่ง นะครับผมๆต้องทำอย่างไรครับผมใช้ l10n_th_withholding_tax_cert (12.0.1.0.2) , l10n_th_withholding_tax_cert_form(12.0.1.0.1) รบกวนชี้แนะด้วยนะครับผม somchart.j@scgl.co.th ขอบคุณครับ
