### ISSUE TITLE
[13.0][TODO] Tax ID Validation & Get or check Tax ID with RD/DBD website

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#71]

**Comment by kittiu** [comment]
เคสนี้มีรายละเอียดอย่างไรครับ มีใครเขียนความต้องการได้ไม๊
หรือมีใครทำไว้แล้วอยากแชร์ครับ

**Comment by poonlap** [comment]
เข้าใจว่ามี api ของ DGA ให้ใช้ครับ แต่ไม่แน่ใจว่าอนุญาตให้บุคคลทั่วไปหรือเอกชนใช้หรือไม่ ดูเว็บ DGA คร่าวๆน่าจะสมัครค่อนข้างยุ่งยากครับ

https://kb.dga.or.th/s/bka3ktp5f5rbi2f1ccpg/suunyklaangaelkepliiynkh-muulphaakhrath-government-data-exchange-center-gdx/d/bn9p0q95f5rcisvhh8fg/kh-muulnitibukhkhl-krmphathnaathurkicchkaarkhaa-dbd
