### ISSUE TITLE
[13.0][TODO] เงินมัดจำ -- จ่าย 100%, จ่ายก่อน 30% ทีหลังจ่าย 70% รวมถึงเงินรับประกันผลงาน Odoo มีเงินมัดจำแต่ไม่ครบ

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#72]

**Comment by sansirit** [comment]
จ่าย 100%, และจ่ายก่อน 30% ทีหลังจ่าย 70%

เราน่าจะสามารถไปเพิ่ม payment terms ได้ครับ ในเมนู Accounting / Configuration / Invoicing / Payment Terms

ส่วนการรับประกันผลงาน ถ้าเป็นการ warranty อาจจะต้องไปใช้ flow ในเรื่อง RMA  ของ OCA มีอยู่ที่นี้ [OCA/rma](https://github.com/OCA/rma)

**Comment by Oakyman** [comment]
@sansirit Payment Terms ของ Odoo คิดว่าขาดอะไรไปบางอย่าง ตอนผมลองใน v11
ตอนนี้ยังนึกรายละเอียดไม่ออก เดี๋ยวนึกออกจะมาเพิ่ม comment อีกทีครับ

แต่เคสนี้คิดว่าอาจจะต้องมีหลายรูปแบบมาก เท่าที่ผมนึกออก

- จ่ายก่อน n%, จ่าย (100-n)% ก่อนส่ง
- จ่ายก่อน n%, จ่าย (100-n)% แบบมีเครดิต d วัน
- จ่ายก่อน n%, จ่าย (100-n)% แบบ L/C (Export)
