### ISSUE TITLE
[13.0][TODO] แยก RFQ / Purchase Order ออกจากกัน เพื่อให้มี Sequence แยกด้วย

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#75]
เคสนี้ผมเสนอให้สร้างโมดูล purchase_isolated_validation เพื่อยแก RFQ / PO
มีตัวอย่างคล้ายกันที่ https://github.com/OCA/sale-workflow/tree/12.0/sale_isolated_quotation

**Comment by kittiu** [comment]
@beemoza @kiattipong
สนใจลองดูอันนี้ไม๊ครับมันมีตัวอย่างแล้ว sale_isolated_quotation ใช้กันมาหลายรุ่น ค่อนข้างถือว่าเสถียร

**Comment by Oakyman** [comment]
@kittiu ขอ define wording ที่ชัดเจนครับ เพราะค่อนข้างขัดกับ business ทั่วไป
RFQ ในที่นี้หมายถึง Draft PO หรือ PO ที่ยังไม่อนุมัติ ซึ่งจะ Run no. แยกจาก PO ที่อนุมัติแล้ว

เพราะปกติใน business ทั่วไป RFQ หมายถึงเอกสาร Request for Quotation ซึ่งจะมีแค่ Product, Qty ไม่มี Unit price, Amount ครับ ในกรณีทั่วๆ ไปอาจจะยังไม่ระบุ Vendor ตอนทำ (คือทำใบเดียวส่งให้ Vendor ทุกราย)

**Comment by kittiu** [comment]
ผมอ้างจาก Odoo มาตรฐานเลยนะครับ สำหรับ Request for Quotation กับ Purchase Oder มันเป็นเอกสารเดียวกันเพียงแต่เปลี่ยน state ครับ (คำเรียกของ Odoo อาจจะต่างจากธุรกิจในไทยได้)

![image](https://user-images.githubusercontent.com/1973598/72892112-53bc2400-3d48-11ea-8309-840df19e20b3.png)

หรือจะเป็น Purchase Agreement (purchase.requisition) นะครับ เอกสารนี้ยังไม่ต้องใส่ Vendor

ส่วนที่คุณ @Oakyman พูดถึง น่าจะเป็น Purchase Request รึเปล่าครับ โดย PR ไม่ต้องใส่ Vendor และเป็นเอกสารตั้งต้นจากพนักงานที่ต้องการของ โดยที่ไม่ต้องรู้ราคาหรือผู้ขายเลยและหลาย PR Line อาจรวมกันมาเป็น 1 RFQ ก็ยังได้
https://github.com/OCA/purchase-workflow/tree/12.0/purchase_request

Note: อาจจะเกินเลยประเด็นความต้องการใน Issue นี้รึเปล่าครับ

**Comment by kongrattapong** [comment]
ผมทำขึ้นมาแล้วตามลิ้งค์นี้นะครับ : https://github.com/OCA/purchase-workflow/pull/851
โดยอิงจาก https://github.com/OCA/sale-workflow/tree/12.0/sale_isolated_quotation
