### ISSUE TITLE
[13.0][TODO] Bank Transfer

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#78]
เพื่อโอนย้ายเงินระหว่างธนาคารหรือนำเงินสดฝาก/ถอนจากธนาคาร โดยไม่ต้องบันทึก Journal ตรง

**Comment by kittiu** [comment]
จริงๆเคสนี้น่าจะใช้งานได้อยู่แล้วใน version ใหม่ๆ เคยใช้ในโปรเจคจริงแล้วก็ใช้ได้ดี (เคยใช้ไม่ได้ใน version เก่า เช่น v8)

เลือกเป็น Internal Transfer ระบบจะให้เลือก Journal ต้นทาง กับ ปลายทาง (account ต้นทาง กับปลายทาง)

![image](https://user-images.githubusercontent.com/1973598/73121795-908a5400-3fb0-11ea-805d-e63c389abdc5.png)

![image](https://user-images.githubusercontent.com/1973598/73121796-92ecae00-3fb0-11ea-9447-961ba18d7002.png)

ไม่แน่ใจว่าเพียงพอไม๊ (ถ้าพอจะขอปิดเคส)

**Comment by kittiu** [comment]
ปัญหาของหน้าต่าง Transfer ปัจจุบัน
* ยังไม่สามารถใส่ Fee ค่า bank charge ได้
* ทำงานได้ทีละรายการ

ข้อเสนอ หากสร้าง Addon เพิ่ม:
* Fee
* Batch Transfer

**Comment by Saran440** [comment]
ควรจะเพิ่ม 2 module ใส่ใน repo : account_payment ใน OCA
- account_payment_transfer_fee -> ใช้สำหรับการบันทึกบัญชีค่าธรรมเนียม (ไม่มีกรณีที่เป็น multi?)
- account_payment_transfer_batch -> ใช้สำหรับการ transfer หลายๆ bank พร้อมกัน

**Comment by kittiu** [comment]
คิดว่าไม่มีนะ multi
อีกอย่าง คือพี่อยากให้ลองดูว่าเราจะไป reuse feature ของ writeoff ปกติของ account.payment มาใช้เป็น fee ได้ไม๊ อาจแค่เปิดมันขึ้นมาก็ได้นะ (มันปิดไปถ้า payment type = internal transfer)

Note: จริงๆพี่เพิ่งเสนอ PR account_payment_multi_deduction ไป สำหรับ multi แต่คิดว่าไม่น่าต้องใช้กับกรณีนี้ครับ
https://github.com/OCA/account-payment/pull/304 -> เสร็จแล้วขาดแค่ test script กรณี multi currency ว่างๆช่วยรีวิวให้ด้วยนะ :)

**Comment by kittiu** [comment]
ตัวอย่างที่เคยทำในโปรเจคอื่น สำหรับกรณี Batch (อยากได้ความเห็นจากคนอื่นๆด้วย)

![image](https://user-images.githubusercontent.com/1973598/73253146-85bd0280-41ee-11ea-9d02-0778cf6fcffc.png)

**Comment by Saran440** [comment]
@kittiu ลองทดสอบแล้ว สามารถ reused ได้ แต่ยากนะครับ
1. amount ของ payment_difference เป็น compute fields ดูค่าจาก invoice
2. ต้องเลือก payment difference เป็น Mark invoice as fully paid ระบบจึงจะบันทึกบัญชีให้

มีข้อสงสัยเกี่ยวกับการบันทึกบัญชีครับ
ปกติแล้วการทำ Transfer ของระบบ Odoo จะมีการทำงานเป็นแบบ
`Bank ต้นทาง -> ตัวกลาง -> Bank ปลายทาง`
ถ้าต้องการโอนจาก Bank A -> B 100 บาท มีค่าธรรมเนียม 10 บาท
ระบบควรจะบันทึกบัญชีอย่างไร

บันทึกจาก Bank A -> ตัวกลาง
![Selection_013](https://user-images.githubusercontent.com/20896369/73258561-88bcf080-41f8-11ea-886e-1f62faeaefb7.png)

จากตัวกลาง -> Bank B
![Selection_014](https://user-images.githubusercontent.com/20896369/73258572-907c9500-41f8-11ea-909b-f2a4e58e22ec.png)
ซึ่งตรงนี้ระบบควรจะบันทึกเป็น 90, 90 หรือเปล่าครับ หรือบันทึกถูกอยู่แล้ว

**Comment by kittiu** [comment]
ขึ้นอยู่ว่า **Deduct From** จาก Bank ไหน ก็บันทึกตรงนั้น

**Comment by wipawii** [comment]
จากที่เคยทำ ระบบ Odoo ปัจจุบันใช้งานได้อยู่แล้ว ค่าธรรมเนียมก็ไปทำรายการปรับปรุงเพิ่มเติม

แต่ถ้าจะทำให้ใช้งานได้สะดวกขึ้น ควรสามารถบันทึกผลต่าง การโอนระหว่างธนาคารได้มากกว่า 1 บัญชี เผื่อใช้ในกรณี โอนระหว่าง บัญชีไทยบาท กับ FCD แล้วต้องการบันทึก gain/loss exchange rate กับ bank fee

ถ้าจะเพิ่มเติม คือ สามารถ export/import ได้ สำหรับกิจการที่ต้องการทำรายการโอนระหว่างบัญชีกระแสรายวันกับออมทรัพย์ เพราะอาจมีจำนวนรายการเยอะ

**Note** Odoo จะบันทึกผ่านรายการพัก ฉะนั้น CoA ต้องมีบัญชีพักการโอน และเมื่อทำการโอน 1 รายการ Odoo จะสร้าง คู่บัญชี 2 คู่เสมอ
ตัวอย่างเช่น โอนจาก Bank A ไป Bank B 100
Dr    Bank B   100
   Cr    บัญชีพัก   100
Dr    บัญชีพัก  100
   Cr    Bank A    100
Consequence: ถ้ามีการโอนเยอะ รายงาน GL ของบัญชีพักจะเยอะมาก และมี Journal entry เยอะ

**ขอความเห็น** มีใครมีประสบการณ์เรื่องนี้ไหมคะ ที่ Odoo บันทึกแบบนี้รับได้ไหม

**Comment by Saran440** [comment]
ลักษณะการทำงานของ การบันทึกค่าธรรมเนียมจะเป็นแบบนี้นะครับ (ไม่แน่ใจว่าควรจะบันทึก account fee กับ account ที่มีการจ่ายค่าธรรมเนียมอยู่ใน journal entry เดียวกันหรือเปล่า)

Example 1: Transfer, BANK1 -> BANK2 (fee on BANK1):

        Account             | Debit     | Credit
        =========================================================
        Journal Entry 1
        ---------------
        BANK1               |           |   1000.0
        BANK1               |           |     10.0        --> Fee
        ACCOUNT FEE         |     10.0  |
        TRANSFER            |   1000.0  |

        Journal Entry 2
        ---------------
        TRANSFER            |           |   1000.0
        BANK2               |   1000.0  |

Example 2: Transfer, BANK1 -> BANK2 (fee on BANK2):

        Account             | Debit     | Credit
        =========================================================
        Journal Entry 1
        ---------------
        BANK1               |           |   1000.0
        TRANSFER            |   1000.0  |

        Journal Entry 2
        ---------------
        TRANSFER            |           |   1000.0
        BANK2               |   1000.0  |
        ACCOUNT FEE         |     10.0  |
        BANK2               |           |     10.0        --> Fee


สามารถทดสอบได้ที่ https://github.com/OCA/account-payment/pull/309

**Comment by Saran440** [comment]
การโอนเงินต่างธนาคารหลายๆรายการ (Batch Transfer)
สามารถทดสอบได้ที่ https://github.com/OCA/account-payment/pull/317

Note : This module depend on account_payment_fee_transfer (https://github.com/OCA/account-payment/pull/309)
