### ISSUE TITLE
การแปลภาษาไทยสำหรับ Localization Addons

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#80]
Odoo แปลภาษาด้วย Weblate แต่ปัจจุบันยังไม่มีการทำงานในส่วนนี้ คนที่สนใจสามารถเริ่มได้จาก

https://translation.odoo-community.org

สำหรับ Thailand
* https://translation.odoo-community.org/projects/l10n-thailand-12-0
* https://translation.odoo-community.org/projects/l10n-thailand-13-0/.

**Comment by alexezodoo** [comment]
ดีคับ อันนี้ผมพอช่วยได้ จะช่วยแปลน่ะคับ

**Comment by sansirit** [comment]
ผมขอเสนอ แนวทาง (guideline) ในการแปล ดังนี้ครับ

- ลบการแปลภาษาไทยทั้งหมด จาก UI ใน technical menu และ developer mode เพราะสำหรับผู้ใช้งานที่สิทธิใช้งาน developer mode ควรจะสามารถใช้ UI ภาษาอังกฤษได้ และการแปลศัพท์เทคนิคให้เป็นภาษาไทย มักทำให้เกิดความสับสน เช่น
--  `Server Actions` ==> `การดำเนินการของเซิร์ฟเวอร์` แต่ `Automated Actions` ==> `การกระทำอัตโนมัติ` 
- แยกคำแปล ของคำภาษาอังกฤษคำเดียวกัน ในแต่ละการใช้งานได้ เช่น คำว่า Done ของ `state` กับคำว่า Done ของ `quantity_done` ใน form view ของ delivery order [ที่นี้](https://demo.odoo.com/web?debug=1#action=614&active_id=2&cids=1&id=21&menu_id=435&model=stock.picking&view_type=form)
- ควรรวมคำแปลของ community modules ทั้งหมดไว้ในไฟล์ th.po ไฟล์เดียว รวมทั้ง modules ที่มีการใช้งานน้อยด้วย เช่น fleet หรือ lunch
