### ISSUE TITLE
First name for Thai localization

### ISSUE THREAD

**Issue by sansirit** [OCA/l10n-thailand#83]
ระบบของ Odoo ตาม default ไม่ได้แยกชื่อเป็นหลายช่อง ซึ่งก็เป็นทั้งข้อดีและข้อเสีย
ขัดดีคือระบบง่าย
ข้อเสียคือ ผู้ใช้ในเมืองไทย คุ้ยเคยกับระบบที่มีการแยกชื่อเป็นหลายช่อง อีกทั้งการเชื่อมต่อข้อมูลไปยังระบบอื่น โดยเฉพาะระบบภาครัฐของประเทศไทย มักจะถูกกำหนดให้แยกชื่อเป็นหลายช่อง คือ คำนำหน้าชื่อ (prefix) ชื่อ (first name) และนามสกุล (surname) 

ทั้งนี้ระบบมาตรฐานของ Odoo ใน res.partner มี res.title เป็นคำนำหน้าชื่ออยู่แล้ว แต่ไม่ได้แยกข้อมูล ชื่อ ออกจากนามสกุล 

อย่างไรก็ตาม OCA ก็มี module ที่เพิ่ม feature นี้อยู่แล้วคือ [partner_firstname](https://github.com/OCA/partner-contact/tree/13.0/partner_firstname)
ที่แยก firstname กับ lastname ออกจากช่อง name แล้วเปลี่ยน name ให้เป็น computed field ไปเพื่อให้ compatible กับ module อื่นๆ 

ผมคิดว่าสำหรับ Thai localization อาจจะรวม module [partner_firstname](https://github.com/OCA/partner-contact/tree/13.0/partner_firstname) เข้ามาเป็น dependency ของ [l10n_th](https://github.com/odoo/odoo/tree/13.0/addons/l10n_th)

**Comment by kittiu** [comment]
โมดูล partner_fistname อย่างเดียว จะถือว่าสมบูรณ์สำหรับไทยหรือไม่ หรือว่ามีใครทราบไม๊ว่าส่วนใหญ่ในประเทศไทย ต้องการรายการอะไรบ้าง (ได้ยินบางคนว่าราชการไทยมีหลักการอยู่)

อยากเสนอว่า ถ้าเราสามาถสรุปได้แบบมีหลักการ เราสามารถ List ทั้งหมดที่ต้องการใน Issue นี้ได้นะ (รบกวนผู้รู้จริง) เช่น 
1.  ชื่อ first_name
2. นามสกุล last_name
3. คำนำหน้า title_id (res.title) -> (ซึ่งถ้ามีไทยมีอะไรบ้าง ทำเป็น data ไว้ให้เลือกได้)
4. และอื่นๆ

แล้วค่อยมาดูกันว่าต้องเพิ่มอะไร และการ deploy ใช้จริงจะเป็นอย่างไร

IMHO:
* สำหรับเรื่องฟิลด์ en/th ใน software อื่นๆอาจมีการแยก firstname_th, firstname_en. แต่สำหรับ Odoo ควรให้ใช้ translation feature แทนเพื่อให้ตามมาตรฐาน
* l10n_th เป็นของ Odoo S.A. ถ้าอยากเปลี่ยนต้องคุยกับ Odoo ซึ่งเค้าไม่น่าจะยอมมา depend on OCA modules (module เค้าจะกลายเป้น AGPL ตาม OCA) ผมคิดว่าเราทำอันใหม่เลยดีกว่า
* เรื่อง Chart of Account มาตรฐานก็ควรเปิดเป็นอีก Issue นึง ของปัจจุบันผมคิดว่าไม่ตอบโจทย์ เราทำใหม่เลยเช่น l10n_th_oca

**Comment by sansirit** [comment]
- เราควรเพิ่ม data file ของ res.title โดยใส่รายการเข้าไปให้เยอะพอสมควร แต่อาจจะไม่ต้องใส่ทั้งหมด เพราะจะมีคำนำหน้าที่ผสมกันหลายๆ อย่าง ที่มีคนจำนวนน้อยใช้ ซึ่งเราก็ไม่ควรเพิ่มให้ควรทุกกรณี 

- ส่วนการแปลงชื่อ firstname_th, firstname_en ผมกลับคิดว่าชื่อเป็นคำเฉพาะ และชื่อแต่ละคนอาจจะใช้ตัวสะกดภาษาอังกฤษไม่เหมือนกัน ถึงแม้จะสะกดภาษาไทยเหมือนกัน ผมจึงคิดว่าไม่ควรใช้ feature การแปลงภาษา แต่จะเพิ่มให้มีทั้ง th/en หรือไม่ เราอาจจะทำเป็น setting ให้สามารถเลือกได้ในการ config

**Comment by Oakyman** [comment]
เนื่องจาก name ใน res.partner ใช้เก็บทั้ง person และ company
ผมเห็นว่า ควรมี field first_name, last_name เพิ่มเติม
แล้ว name เดิมเป็น compute field
กรณี company จะไม่ได้มีแต่ prefix แต่มี suffix ด้วย เช่น บริษัท ... จำกัด, บริษัท ... จำกัด (มหาชน), หจก.

**Comment by ps-tubtim** [comment]
มีความเห็นว่าโมดูล l10n_partner_firstname ควรมีลักษณะ ดังนี้
- depend partner_firstname (ซึ่งมีฟิลด์ firstname, lastname และมีการ compute name แล้ว)
- เพิ่ม res.partner.title ซึ่งจะต้องมาตัดสินใจว่าควรมีลักษณะอย่างไร เป็นภาษาไทยเท่านั้น หรือ เป็นภาษาอังกฤษเท่านั้น หรือ เพิ่มทั้ง 2 ภาษา หรือ เป็น 2 ภาษาใน record เดียว
- อาจจะมีการเพิ่ม res.partner.title เข้าไปใน name ด้วย 

การใช้งาน
- บันทึกชื่อ partner เป็นภาษาใดภาษาหนึ่งเพียงอย่างเดียว เนื่องจากการออกเอกสารต่างๆที่ใช้ชื่อของ partner น่าจะมีการใช้เพียงภาษาเดียวเท่านั้น
- ในกรณี Company ก็ให้พิมพ์ชื่อเต็มที่ฟิลด์ name ไปเลย โดยไม่ต้องใช้การ compute

**Comment by ghost** [comment]
> * สำหรับเรื่องฟิลด์ en/th ใน software อื่นๆอาจมีการแยก firstname_th, firstname_en. แต่สำหรับ Odoo ควรให้ใช้ translation feature แทนเพื่อให้ตามมาตรฐาน

ในกรณีที่ใช้การ translation ของ fields name เราสามารถทำ name_search ได้ทั้งสองภาษาหรือเปล่าครับ
แล้วในกรณีนี้ fields name เราจะเก็บข้อมูลที่เป็น Eng แล้วภาษาไทยใช้การ translation ใช่ไหมครับ

ปล.ผมกำลังหา solution สำหรับการเก็บข้อมูล Employees บน v13

**Comment by kittiu** [comment]
เคยทำใน v8 เพราะองค์กรใหญ่ขอมาใช้ (เพราะเรายืนยันว่าไม่ควรแยกฟิลด์เป็นป name_en, name_th เพราะจะให้กระทบกับส่วนอื่นๆหนักเลย เช่น ตามรายงาน หรือตามที่ๆ employee ถูกเรียกใช้) เลยมียุ่งยากในการทำงานถ้าจะต้องมาคอยกลับภาษา เป็นฟีเจอร์ที่น่าสนใจทำนะ

ผมคิดว่าน่าทำแต่ก็ควรแยกเป็นอีกโมดูลนึง และ search หลายภาษาไม่เฉพาะไทย และได้ทั้งระบบไม่จำกัดเฉพาะ employee
Note: ที่เราไม่ควรเอาทุกอย่างอย่างไว้ที่โมดูลเดียว เพราะไม่ทุกคนที่อยากได้ครับ

ไม่แน่ใจเหมือนกันว่า OCA หลังๆมีไม๊ ลองหาดูก่อน ถ้าไม่มีเราสามารถทำ PR ขึ้นไปเสนอได้ครับ ถ้ามีไอเดีย สามารถลองทำขึ้นมาได้นะครับ เราจะได้ร่วมมือกันช่วยกันทดสอบ :)

**Comment by kittiu** [comment]
Issue นี้เสร็จแล้ว (สำหรับ res.partner นะ ยังไม่เกี่ยวกับเรื่องการแปล อันนั้นคงต้องแยกไป)
https://github.com/OCA/l10n-thailand/pull/95
รบกวนรีวิวและกด Approve
2 approved สามารถ merge ได้
ขอบคุณครับ
