### ISSUE TITLE
รับชำระเงินจากลูกค้ามากกว่า 1 Invoice และต้องออกใบเสร็จรับเงิน/ใบกำกับภาษีใบเดียว ข้อมูลใบกำกับภาษีไม่เป็นไปตามกรมสรรพากรกำหนด

### ISSUE THREAD

**Issue by wipawii** [OCA/l10n-thailand#87]
**Requirement:** รายการที่ต้องมีในใบกำกับภาษีเต็มรูป ต้องแสดง  ชื่อ ชนิด ประเภท ปริมาณ และมูลค่าของสินค้าหรือบริการ
Case: ใบแจ้งหนี้หลายใบ รวบจ่ายครั้งเดียว และในแต่ละใบแจ้งหนี้มีรายการมากกว่าหนึ่งบรรทัด
**ตัวอย่าง:**
* ใบแจ้งหนี้ เลขที่ 001 มี 2 รายการ (110+7.70 = 117.70 บาท)
  * บริการ A จำนวน 10 หน่วย ราคาหน่วยละ 10 บาท รวม 100 บาท
  * บริการ B จำนวน 5 หน่วย ราคาหน่วยละ 2 บาท รวม 10 บาท
* ใบแจ้งหนี้ เลขที่ 002 มี 1 รายการ (100+7 = 107.00 บาท)
** บริการ B จำนวน 50 หน่วย ราคาหน่วยละ 2 บาท รวม 100 บาท

**ปรึกษา:** ใบเสร็จรับเงิน/ใบกำกับภาษี จ่ายรวม (224.70 บาท) ระบบ Odoo ทำงานได้ แต่ออกรายงานใบเสร็จรับเงิน/ใบกำกับภาษี ให้ลูกค้าอย่างไร

![Selection_551](https://user-images.githubusercontent.com/50727474/72801908-235b8380-3c7d-11ea-9828-f5b947166201.png)
http://www.rd.go.th/publish/fileadmin/user_upload/ebook/taxinvoice.pdf

**Comment by Oakyman** [comment]
กรณีจ่าย Tax Invoice หลายใบ แล้วออก Receipt ใบเดียว
ทางบริษัทผมแยก Receipt ออกมา ไม่รวมกับ Tax Invoice ครับ
ส่วนเท่าที่เห็นจาก Supplier กรณีรวม Tax Invoice หลายใบ Supplier ก็จะแยก Receipt ออกมาต่างหากครับ

กรณีนี้ผมเห็นว่า ต้องแยก definition ของ Invoice และ Tax Invoice ออกจากกัน อาจจะรวมถึง Receipt ด้วย
Receipt ควรอ้างอิง Payment (account.payment) อาจจะให้เลือก Type หรือบังคับโดยระบบว่า
จะออก Receipt เป็น Receipt/Tax Invoice (บริการ) หรือ Receipt (สินค้า) เท่านั้น
ที่ Invoice (account.invoice) อาจจะต้องให้เลือก Type หรือบังคับโดยระบบว่า
จะออก Invoice เป็น Invoice/Tax Invoice (สินค้า) หรือ Invoice (บริการ) เท่านั้น
อันนี้ผมอ้างอิงประสบการณ์จากที่เคยเจอลูกค้าสมัยทำ Software House หลายปีก่อนครับ

กรณีลูกค้ารายนี้ ตรงรายการใน Receipt ผมว่าต้องลิสต์รายการใน Invoice แต่ละใบขึ้นมาด้วย
(โดยปกติกรณีจ่ายรวบ จะแสดงแค่ Invoice no., Invoice Date, Invoice Amount)
อาจจะแสดงเป็น Invoice no., Invoice Date, Product, Quantity, Amount

**Comment by wipawii** [comment]
@Oakyman ขอบคุณนะคะ ที่แชร์ประสบการณ์จริงๆ ก็คล้ายกันนะคะ คือ

ขายสินค้า
- account.invoice > print Invoice/Tax invoice
- account.payemnt > print Receipt
บริการ
- account.invoice > print Invoice
- account.payemnt > print Receipt/Tax invoice

แต่ที่ไปต่อไม่ถูก คือ บริการค่ะ รวบจ่ายหลาย invoice พอเป็น receipt/tax invoice ที่ account.payment สิ่งที่แสดงอย่างที่บอกเลยคะ แสดง invoice no. แต่ไม่มีรายละเอียดบริการ (อ้างอิงตามภาพissue ข้อกำหนด ใบกำกับภาษี ข้อ 5 ใบกำกับภาษีต้องมี)  แก้ไขปัญหาโดย ไปดึง Invoice line มา ก็จะใช้ได้สำหรับ 1:1 จ่ายรวบ ก็ต้องออกแยกตาม invoice เวลาทำ bank reconciliation กับ bank statement ก็จะชนตัวเลขรับเงินยาก เพราะโอนมาก้อนเดียว แต่ระบบบันทึกแยก

ทุกวันนี้ก็ออก receipt/tax invoice หลายใบตาม invoice รบกวนลูกค้าปรับตัวแทน

**Comment by wattanadev** [comment]
ในกรณี invoice ประเภทบริการ แล้วรวบจ่ายหลายใบ เพื่อออก Receipt/Tax invoice ใบเดียว จำเป็นต้องมีรายการสินค้าและบริการใน Receipt/Tax invoice ด้วยครับ

![image](https://user-images.githubusercontent.com/1023281/73325686-ff520080-4281-11ea-8e82-e42d628880ab.png)
![image](https://user-images.githubusercontent.com/1023281/73325705-0f69e000-4282-11ea-8267-4a086afc6662.png)
![image](https://user-images.githubusercontent.com/1023281/73325711-198bde80-4282-11ea-9e16-f3f380664fa4.png)

**Comment by wipawii** [comment]
@wattanadev ขอบคุณมากค่ะ

การเขียนคือ ดึง invoice.line มาเรียงต่อกันที่ Receipt/Tax Invoice Report ใช่ไหมคะ แล้วถ้า มีหลาย Line ก็เรียงๆ กันไปใช่ไหมคะ

ไม่ทราบว่าเคยเจอกรณีที่จ่ายเพียงบางส่วน แต่หลาย Invoice ไหมคะ

**Comment by wattanadev** [comment]
ใช่ครับ ดึงมาเรียงกัน แล้วแก้ไขยอดที่จะจ่ายได้ตาม invoice ครับ
![image](https://user-images.githubusercontent.com/1023281/73326944-915c0800-4286-11ea-9a48-b6199edfb93d.png)

**Comment by nanond** [comment]
ผมขอคำปรึกษาครับ คือตอนนี้ทำใบแจ้งหนี้ได้ ระบบเกือบสมบูรณ์แล้วครับแต่ออกใบกำกับภาษีกับใบเสร้จรับเงินได้ไม่ ใครสะดวกช่วยผมหน่อยครับ เครื่องผม OCA V.15 On Ubuntu server  ขอบคุณครับ
