### ISSUE TITLE
[13.0][FIX] l10n_th_tax_report, error on install ยังผมปัญหาในการลง modules

### ISSUE THREAD

**Issue by Boss1669** [OCA/l10n-thailand#89]
[13.0][FIX] l10n_th_tax_report, error on install ยังผมปัญหาในการลง modules อยู่ครับ

```
  File "/odoo/odoo-server/odoo/fields.py", line 3137, in _setup_regular_full
    raise TypeError(msg % (self, field))
TypeError: Many2many fields tax.report.view.sale_line_ids and account.move.line.sale_line_ids use the same table and columns
```

**Comment by kittiu** [comment]
ใช่แล้วครับ เพราะยัง merge ตัวแก้เข้าไปไม่ได้ https://github.com/OCA/l10n-thailand/pull/66
เนื่อจากยังติดอีก dependency ชื่อ report_xlsx_helper, PR นั้นยังไม่ได้รับการ merge
https://github.com/OCA/reporting-engine/pull/361

ไม่งั้นต้องไปใช้ตัวที่เป็น PR มาลองไปก่อน
https://github.com/ecosoft-odoo/l10n-thailand/tree/13.0-fix-l10n_th_tax_report-error_install/l10n_th_tax_report

ต้องรอซักพักครับ เพราะคนใน community ที่ทำหน้าที่ merge อาจติดงานอื่นอยู่

**Comment by Boss1669** [comment]
@kittiu ใช่ครับ error ที่แจ้งมา ก็มาจากตัว PR [](https://github.com/ecosoft-odoo/l10n-thailand/tree/13.0-fix-l10n_th_tax_report-error_install/l10n_th_tax_report) ตามที่คุณ @kittiu แจ้งมาครับ ก็เลยยังสงสัยว่าตัวที่แก้แล้วน่าจะไม่มีปัญหาครับ หรือ ต้องรอ merge อย่างเดียว

**Comment by Boss1669** [comment]
แก้ไขได้แล้วครับขอบคุณครับ
