### ISSUE TITLE
[13.0, 12.0][BUG] Purchase VAT Report ไม่ควรแสดงค่าติดลบ

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#96]
![image](https://user-images.githubusercontent.com/1973598/74136412-8c9d3980-4c20-11ea-84ce-3577422e323c.png)

cc @kongrattapong

**Comment by kongrattapong** [comment]
V13 - https://github.com/OCA/l10n-thailand/pull/101

V12 - https://github.com/OCA/l10n-thailand/pull/102
